<?php

/**
 * Aggressive autoloader fix - removes references to missing files
 * This should be run BEFORE any artisan commands
 */

$vendorDir = __DIR__ . '/vendor';
$composerDir = $vendorDir . '/composer';
$autoloadFiles = $composerDir . '/autoload_files.php';
$autoloadStatic = $composerDir . '/autoload_static.php';

echo "Fixing broken autoloader references...\n";

// Fix autoload_files.php
if (file_exists($autoloadFiles)) {
    $content = file_get_contents($autoloadFiles);
    $files = [];
    
    // Extract the files array
    if (preg_match('/return\s+array\s*\((.*?)\)\s*;/s', $content, $matches)) {
        $arrayContent = $matches[1];
        // Parse the array entries
        preg_match_all("/'([^']+)'\s*=>\s*\$vendorDir\s*\.\s*'([^']+)'/", $content, $fileMatches, PREG_SET_ORDER);
        
        $fixedFiles = [];
        foreach ($fileMatches as $match) {
            $key = $match[1];
            $path = $match[2];
            $fullPath = $vendorDir . $path;
            
            if (file_exists($fullPath)) {
                $fixedFiles[] = "    '{$key}' => \$vendorDir . '{$path}',";
            } else {
                echo "Removing missing file reference: {$path}\n";
            }
        }
        
        // Rebuild the file
        $newContent = "<?php\n\n// autoload_files.php @generated by fix-autoloader.php\n\n\$vendorDir = dirname(__DIR__);\n\nreturn array(\n" . implode("\n", $fixedFiles) . "\n);\n";
        file_put_contents($autoloadFiles, $newContent);
        echo "Fixed autoload_files.php\n";
    }
}

// Fix autoload_static.php
if (file_exists($autoloadStatic)) {
    $content = file_get_contents($autoloadStatic);
    
    // Find and remove references to missing files
    if (preg_match_all("/'([^']+)'\s*=>\s*__DIR__\s*\.\s*'([^']+)'/", $content, $matches, PREG_SET_ORDER)) {
        $removed = 0;
        foreach ($matches as $match) {
            $key = $match[1];
            $path = $match[2];
            $fullPath = $composerDir . $path;
            
            if (!file_exists($fullPath)) {
                // Remove this line
                $pattern = "/'{$key}'\s*=>\s*__DIR__\s*\.\s*'{$path}',?\s*\n/";
                $content = preg_replace($pattern, '', $content);
                $removed++;
                echo "Removed missing file from autoload_static.php: {$path}\n";
            }
        }
        
        if ($removed > 0) {
            file_put_contents($autoloadStatic, $content);
            echo "Fixed autoload_static.php (removed {$removed} references)\n";
        }
    }
}

// Now try to regenerate properly
echo "Regenerating autoloader...\n";
exec('composer dump-autoload --optimize --no-interaction 2>&1', $output, $return);

if ($return === 0) {
    echo "Autoloader regenerated successfully.\n";
} else {
    echo "WARNING: Could not regenerate autoloader automatically.\n";
    echo "Output: " . implode("\n", $output) . "\n";
}

// Final check - try to load autoloader
if (file_exists($vendorDir . '/autoload.php')) {
    try {
        // Use a custom error handler to catch missing file errors
        set_error_handler(function($errno, $errstr, $errfile, $errline) {
            if (strpos($errstr, 'Failed to open stream') !== false || 
                strpos($errstr, 'Failed opening required') !== false) {
                // This is the error we're trying to fix
                return true; // Suppress the error
            }
            return false; // Let other errors through
        }, E_WARNING | E_ERROR);
        
        require $vendorDir . '/autoload.php';
        restore_error_handler();
        echo "Autoloader can now be loaded.\n";
    } catch (Throwable $e) {
        restore_error_handler();
        echo "ERROR: Autoloader still broken: " . $e->getMessage() . "\n";
        echo "You may need to run: composer install --no-scripts && composer dump-autoload\n";
        exit(1);
    }
}

echo "Autoloader fix completed.\n";
exit(0);

