<?php

/**
 * Aggressive autoloader fix - directly removes broken file references
 * Run this BEFORE any PHP code that uses the autoloader
 */

$vendorDir = __DIR__ . '/vendor';
$composerDir = $vendorDir . '/composer';

echo "Fixing broken autoloader references...\n";

// Fix autoload_files.php by removing references to missing files
$autoloadFiles = $composerDir . '/autoload_files.php';
if (file_exists($autoloadFiles)) {
    $content = file_get_contents($autoloadFiles);
    
    // Parse the file to extract file references
    $files = [];
    if (preg_match('/return\s+array\s*\((.*?)\)\s*;/s', $content, $matches)) {
        // Extract individual file entries
        preg_match_all("/'([^']+)'\s*=>\s*\\\$vendorDir\s*\.\s*'([^']+)'/", $content, $fileMatches, PREG_SET_ORDER);
        
        $validFiles = [];
        $removed = 0;
        
        foreach ($fileMatches as $match) {
            $key = $match[1];
            $relativePath = $match[2];
            $fullPath = $vendorDir . $relativePath;
            
            if (file_exists($fullPath)) {
                $validFiles[] = "    '{$key}' => \$vendorDir . '{$relativePath}',";
            } else {
                echo "Removing missing file: {$relativePath}\n";
                $removed++;
            }
        }
        
        if ($removed > 0) {
            // Rebuild the file with only valid entries
            $newContent = "<?php\n\n// autoload_files.php @generated by fix-autoloader-aggressive.php\n\n\$vendorDir = dirname(__DIR__);\n\nreturn array(\n" . implode("\n", $validFiles) . "\n);\n";
            file_put_contents($autoloadFiles, $newContent);
            echo "Removed {$removed} broken file references from autoload_files.php\n";
        }
    } else {
        // Fallback: line-by-line approach
        $lines = explode("\n", $content);
        $fixedLines = [];
        $removed = 0;
        
        foreach ($lines as $line) {
            if (preg_match("/=>\s*\\\$vendorDir\s*\.\s*'([^']+)'/", $line, $matches)) {
                $filePath = $matches[1];
                $fullPath = $vendorDir . $filePath;
                
                if (!file_exists($fullPath)) {
                    echo "Removing missing file: {$filePath}\n";
                    $removed++;
                    continue;
                }
            }
            
            $fixedLines[] = $line;
        }
        
        if ($removed > 0) {
            $newContent = implode("\n", $fixedLines);
            file_put_contents($autoloadFiles, $newContent);
            echo "Removed {$removed} broken file references from autoload_files.php\n";
        }
    }
}

// Fix autoload_static.php
$autoloadStatic = $composerDir . '/autoload_static.php';
if (file_exists($autoloadStatic)) {
    $content = file_get_contents($autoloadStatic);
    $removed = 0;
    
    // Remove lines referencing missing files
    $lines = explode("\n", $content);
    $fixedLines = [];
    
    foreach ($lines as $line) {
        if (preg_match("/=>\s*__DIR__\s*\.\s*'([^']+)'/", $line, $matches)) {
            $filePath = $matches[1];
            $fullPath = $composerDir . $filePath;
            
            if (!file_exists($fullPath)) {
                echo "Removing missing file from autoload_static.php: {$filePath}\n";
                $removed++;
                continue;
            }
        }
        
        $fixedLines[] = $line;
    }
    
    if ($removed > 0) {
        $newContent = implode("\n", $fixedLines);
        file_put_contents($autoloadStatic, $newContent);
        echo "Removed {$removed} broken file references from autoload_static.php\n";
    }
}

// Now regenerate the autoloader properly
echo "Regenerating autoloader...\n";
exec('composer dump-autoload --optimize --no-interaction 2>&1', $output, $return);

if ($return === 0) {
    echo "Autoloader regenerated successfully.\n";
} else {
    echo "WARNING: Could not regenerate autoloader:\n" . implode("\n", $output) . "\n";
    echo "You may need to run: composer install --no-scripts && composer dump-autoload\n";
}

echo "Fix completed.\n";
exit(0);

